version: "3.9"

services:
  mickshare:
    build:
      context: .
      network: host
    container_name: "mickshare"
    restart: always
    volumes:
      - ./uploads:/app/upload
    ports:
      - "${PORT}:${PORT}"
